name: DataGSM stage CD workflow

on:
  workflow_run:
    workflows: ["DataGSM stage CI Workflow"]
    types:
      - completed
    branches:
      - 'develop'
      - 'cicd/run-workflows'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CD:
    runs-on: ubuntu-latest
    environment: stage
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false
          gradle-home-cache-cleanup: true

      - name: Make YML Files
        run: |
          mkdir -p ./datagsm-authorization/src/main/resources
          mkdir -p ./datagsm-web/src/main/resources
          mkdir -p ./datagsm-resource/src/main/resources

          touch ./datagsm-authorization/src/main/resources/application-stage.yml
          echo "${{ secrets.STAGE_AUTHORIZATION_APPLICATION_YAML }}" > ./datagsm-authorization/src/main/resources/application-stage.yml

          touch ./datagsm-web/src/main/resources/application-stage.yml
          echo "${{ secrets.STAGE_WEB_APPLICATION_YAML }}" > ./datagsm-web/src/main/resources/application-stage.yml

          touch ./datagsm-resource/src/main/resources/application-stage.yml
          echo "${{ secrets.STAGE_RESOURCE_APPLICATION_YAML }}" > ./datagsm-resource/src/main/resources/application-stage.yml
        shell: bash

      - name: Build with Gradle
        run : ./gradlew build -x test --parallel --build-cache

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Make ZIP File
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Upload to S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./$GITHUB_SHA.zip s3://${{ secrets.AWS_S3_BUCKET_NAME }}/stage/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name datagsm-stage-server-codedeploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name datagsm-stage-server --s3-location bucket=${{ secrets.AWS_S3_BUCKET_NAME }},bundleType=zip,key=stage/$GITHUB_SHA.zip

      - name: CD Success Notification
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_INFORMATION_ALERT_CHANNEL_WEBHOOK }}
          color: 0x4CAF50

      - name: CD Failure Notification
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_INFORMATION_ALERT_CHANNEL_WEBHOOK }}
          color: 0xFF4C4C

      - name: CD Cancelled Notification
        uses: sarisia/actions-status-discord@v1
        if: cancelled()
        with:
          webhook: ${{ secrets.DISCORD_INFORMATION_ALERT_CHANNEL_WEBHOOK }}
          color: 0xFFA500
          title: "üö´ CD Ï∑®ÏÜåÎê®"
